# Generated by Django 5.1.3 on 2024-11-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_edit_post', 'Can Edit Post'), ('can_create_post', 'Can Create Post'), ('can_view_post', 'Can View Post'), ('can_publish', 'Can Publish Post'), ('can_delete_post', 'Can Delete Ppost'), ('can_share_post', 'Can Share Post'), ('can_report_post', 'Can Report Post'), ('can_comment_on_post', 'Can Comment On Post')], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
