# Generated by Django 5.1.3 on 2024-11-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employees_department_alter_employees_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ('first_name',), 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
