# Generated by Django 5.1.3 on 2024-11-21 00:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurOrganizations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_name', models.CharField(max_length=255)),
                ('org_email', models.CharField(max_length=255)),
                ('org_phone_no', models.CharField(max_length=255)),
                ('org_description', models.CharField(blank=True, max_length=255, null=True)),
                ('org_domain', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'db_table': 'organizations_ourorganizations',
            },
        ),
    ]
