# Generated by Django 5.1.3 on 2024-11-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_jobtitle_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.department'),
        ),
    ]
